[Icon Theme]
Name=WhiteSur Apps Only
Comment=WhiteSur application icons only
Inherits=Adwaita

Directories=apps/16,apps/22,apps/32,apps/scalable,apps/symbolic
ScaledDirectories=apps@2x/16,apps@2x/22,apps@2x/32,apps@2x/scalable,apps@2x/symbolic

[apps/16]
Size=16
Context=Applications
Type=Fixed

[apps/22]
Size=22
Context=Applications
Type=Fixed

[apps/32]
Size=32
Context=Applications
Type=Fixed

[apps/scalable]
Size=64
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

